name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim_version: ['stable', 'nightly']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Neovim
      uses: rhymond/setup-neovim@v1
      with:
        neovim-version: ${{ matrix.neovim_version }}
    
    - name: Install Luarocks
      run: |
        sudo apt-get update
        sudo apt-get install -y luarocks
    
    - name: Run tests
      run: make test